name: tap_space
services:
  api:
    container_name: tap_space_api
    build:
      context: ../
      dockerfile: API/Dockerfile
    ports:
      - "8082:8080"
    env_file: .env
    depends_on:
      - db
  db:
    container_name: tap_space_db
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - 6543:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    name: db